version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"

  server:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      DB_URL: ${DB_URL}
