version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"

  server:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_URL: mongodb+srv://eladarmoni:Elad23531@cluster0.fjyltyn.mongodb.net/?retryWrites=true&w=majority

  db:
    image: mongo
